### ISSUE TITLE
Feature request: stack on an already submitted PR

### ISSUE THREAD

**Issue by zasdfgbnm** [ezyang/ghstack#17]
Sometimes I realize I should use stacked diff only after I have already submitted one. It would be good if I can still do a stacked diff, but the base is on a submitted PR.

**Comment by ezyang** [comment]
Yeah, this will be kind of tricky to implement, because ghstack assumes that all diffs have uniform branch format and so if there is an old fashioned PR already it would violate this. Plus, if you submitted your PR in your fork, you are SOL, we cannot implement this at all. My fix for this is to just use ghstack for everything (lol).

**Comment by zasdfgbnm** [comment]
> My fix for this is to just use ghstack for everything (lol).

That is actually a good suggestion!

**Comment by ezyang** [comment]
Would be subsumed by https://github.com/ezyang/ghstack/issues/122
